---
title: "Clonal Evolution Figure 2"
author: "Robert Bowman"
date: "5/12/2022"
output: html_document
---


Setup and Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/LevineLab/Levine Lab/Bobby/Project Notes/Flt3/")
```

Data Sets
```{r, message=FALSE}
library(tidyverse)
library(cowplot)
library(RColorBrewer)
library(pals)
setwd("/Volumes/LevineLab/Levine Lab/Bobby/Project Notes/Flt3/")
source("./Scripts/extra_functions.R")
results_Leuk<-readRDS(file="./Results/2022/February/Flt3_Npm1_3DE_STAR_results.rds")
pheno_select_leuk<-readRDS(file="./Results/2022/February/Flt3_NPM1_3DE_STAR_pheno.rds")
norm_counts_leuk<-readRDS(file="./Results/2022/February/Flt3_NPM1_3DE_STAR_norm_counts.rds")
long_counts_leuk<-readRDS(file="./Results/2022/February/Flt3_NPM1_3DE_STAR_long_counts.rds")
vsd_transformation_leuk<-readRDS(file="./Results/2022/February/Flt3_NPM1_3DE_STAR_vsd.rds")

results_FTime<-readRDS(file="./Results/2022/February/Flt3_3DE_STAR_results.rds")
pheno_FTime<-readRDS(file="./Results/2022/February/Flt3_3DE_STAR_pheno.rds")
norm_counts_FTime<-readRDS(file="./Results/2022/February/Flt3_3DE_STAR_norm_counts.rds")
long_counts_FTime<-readRDS(file="./Results/2022/February/Flt3_3DE_STAR_long_counts.rds")
vsd_transformation_FTime<-readRDS(file="./Results/2022/February/Flt3_3DE_STAR_vsd.rds")
```

Gene lists
```{r}
immediate_response_GMP<-read.csv(file="./Results/2022/February/immediate_response_GMP_genes.csv")[,-1]
sustained_response_GMP<-read.csv(file="./Results/2022/February/sustained_response_GMP_genes.csv")[,-1]
delayed_response_GMP<-read.csv(file="./Results/2022/February/delayed_response_GMP_genes.csv")[,-1]

immediate_response_LSK<-read.csv(file="./Results/2022/February/immediate_response_LSK_genes.csv")[,-1]
sustained_response_LSK<-read.csv(file="./Results/2022/February/sustained_response_LSK_genes.csv")[,-1]
delayed_response_LSK<-read.csv(file="./Results/2022/February/delayed_response_LSK_genes.csv")[,-1]

cutoff<- -log10(0.01)
immediate_LSK_up<-immediate_response_LSK%>%dplyr::filter(Flt3_2w_LSK>cutoff)%>%pull(Genes)
sustained_LSK_up<-sustained_response_LSK%>%dplyr::filter(Flt3_8w_LSK>cutoff)%>%pull(Genes)
delayed_LSK_up<-delayed_response_LSK%>%dplyr::filter(Flt3_4w_LSK>cutoff)%>%pull(Genes)

immediate_GMP_up<-immediate_response_GMP%>%dplyr::filter(Flt3_2w_GMP>cutoff)%>%pull(Genes)
sustained_GMP_up<-sustained_response_GMP%>%dplyr::filter(Flt3_8w_GMP>cutoff)%>%pull(Genes)
delayed_GMP_up<-delayed_response_GMP%>%dplyr::filter(Flt3_4w_GMP>cutoff)%>%pull(Genes)

immediate_LSK_down<-immediate_response_LSK%>%dplyr::filter(Flt3_2w_LSK<(-cutoff))%>%pull(Genes)
sustained_LSK_down<-sustained_response_LSK%>%dplyr::filter(Flt3_8w_LSK<(-cutoff))%>%pull(Genes)
delayed_LSK_down<-delayed_response_LSK%>%dplyr::filter(Flt3_4w_LSK<(-cutoff))%>%pull(Genes)

immediate_GMP_down<-immediate_response_GMP%>%dplyr::filter(Flt3_2w_GMP<(-cutoff))%>%pull(Genes)
sustained_GMP_down<-sustained_response_GMP%>%dplyr::filter(Flt3_8w_GMP<(-cutoff))%>%pull(Genes)
delayed_GMP_down<-delayed_response_GMP%>%dplyr::filter(Flt3_4w_GMP<(-cutoff))%>%pull(Genes)

```

GSEA setup
```{R gene set extraction and setup,cache=TRUE}
library(msigdbr)
library(fgsea)
C2_gene_sets <- msigdbr(species = "Mus musculus", category = "C2")%>%
                          data.frame%>%
                          dplyr::select(gene_symbol,gs_name)%>%
                          split(f = as.factor(.$gs_name))%>%
                          lapply(function(x){x$gene_symbol})
H_gene_sets <- msigdbr(species = "Mus musculus", category = "H")%>%
                          data.frame%>%
                          dplyr::select(gene_symbol,gs_name)%>%
                          mutate(gs_name=gsub("HALLMARK_","",gs_name))%>%
                          split(f = as.factor(.$gs_name))%>%
                          lapply(function(x){x$gene_symbol})
```


Figure 2d
```{r LSk heatmap FLT3 Npm1}
library(tidyheatmaps)

genes_of_interest<- c("Meis1","Tal1","Hoxb5","Mecom",
                      "Hoxa10","Hoxa9","Flt3","Nycn","Ccl5","Hoxa7","Fgfr1","Irf7","Irf8",
                      "Nr4a1","Socs1","Cish","Socs2",
                      "Hoxa7","Hoxa10","Flt3",
                      "Npm1","Cd34")
 

results_Leuk$Flt3_Npm1_LSK$Flt3_Npm1_VS_Flt3%>%
                          data.frame()%>%
                          rownames_to_column(var="Gene")%>%
                        #  filter(Gene%in%genes_of_interest)
                          filter(padj<0.05&(log2FoldChange)>log2(2)*1&baseMean>25)%>%
                          arrange(padj)
  

long_counts_leuk%>%
  filter(Gene%in%genes_of_interest)%>%
  filter(Cell%in%"LSK")%>%
  arrange(Cell,(Genotype), Timepoint)%>%
  tidy_heatmap(rows=Gene,
               columns = Sample,
               values = value,
               scale="row",
               annotation_col =c(Genotype),
               colors = rev(brewer.rdbu(n=100)),
               treeheight_row = 0,
               color_legend_n=100,
               cellwidth = 5,
               cellheight = 7,
               show_colnames = FALSE,
               annotation_colors = list("Genotype"=c("WT"="grey70",
                                                     "Flt3"=brewer.pal(n=5,"Reds")[5],
                                                     "Npm1"=brewer.pal(n=5,"Blues")[5],
                                                     "Flt3_Npm1"=brewer.pal(n=5,"Greens")[5]) ),
               cluster_rows = TRUE,
               file="./Mature_analysis/Final_Figures/Figure 2/Figure 2d-heatmap.pdf")


```

