---
title: "Clonal Evolution scDNA"
author: "Bowman RL"
date: "5/12/2022"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/LevineLab/Levine Lab/Bobby/Project Notes/Flt3/")
```

Packages
```{r libraries}
library(tidyverse)
library(Seurat)
library(scDNA)
library(pals)
library(cowplot)
library(ggrastr)
setwd("/Volumes/LevineLab/Levine Lab/Bobby/Project Notes/Flt3/")
source("./Scripts/extra_functions.R")
```

Data import
```{r}
library(tidyverse)
all_files<- list.files("./scDNA/Processed/")

summary_files<- grep("final_sample_summary_with_p",all_files,value=TRUE)
summary_files<- grep("BB",summary_files,value=TRUE)
sample_names<- do.call(rbind,strsplit(summary_files,split="-"))[,1]
names(summary_files)<-sample_names

cohort_clones<- setNames(lapply(sample_names,function(sample){
  readRDS(paste0("./scDNA/Processed/",summary_files[sample]))
}),sample_names)

names(cohort_clones)
```

```{r}
setwd("/Volumes/LevineLab/Levine Lab/Bobby/Project Notes/Flt3/")

ggsave(scDNA::clonograph(cohort_clones[["BB_2101b"]],complete_only = TRUE),
       width=10*.7,
       height=7*.4,
       file="./Results/2022/May/BB_2101b_clonograph.pdf")

ggsave(scDNA::clonograph(cohort_clones[["BB_3298a"]],complete_only = TRUE),
       width=10*.7,
       height=7*.4,
       file="./Results/2022/May/BB_3298a_clonograph.pdf")

ggsave(scDNA::clonograph(cohort_clones[["BB_4926"]],complete_only = TRUE),
       width=10*.4,
       height=7*.4,
       file="./Results/2022/May/BB_4926_clonograph.pdf")

ggsave(scDNA::clonograph(cohort_clones[["BB_6984a"]],complete_only = TRUE),
       width=10*.7,
       height=7*.4,
       file="./Results/2022/May/BB_6984a_clonograph.pdf")
```

Load the Seurat object
```{r}
s<-readRDS(file="/Users/bowmanr/Projects/Flt3//Data/scDNA/cohort_analysis.rds")
```

CD34 ridgeplot
```{r}
Idents(object = s) <- "Clone_Group"
CD34_ridge<-RidgePlot(s,features=c("CD34"),  
          sort = "decreasing",
          cols = rev(c(brewer.pal(n=5,name="Blues")[3],
                    brewer.pal(n=5,name="Blues")[3],
                    brewer.pal(n=5,name="Reds")[3],
                    brewer.pal(n=5,name="Reds")[3],
                    brewer.pal(n=5,name="Reds")[3],
                    brewer.pal(n=5,name="Reds")[3])),
          idents = rev(c("DNMT3A_FLT3","DNMT3A",
                     "DNMT3A_NPM1_FLT3","DNMT3A_NPM1",
                     "NPM1_FLT3","NPM1"))
)

ggsave(CD34_ridge,
       width=10*.7,
       height=7*.7,
       file="./Results/2022/May/CD34_ridge.pdf")

NPM1c_Vs_WT<-FindMarkers(s,ident.1 = grep("NPM1",levels(Idents(s)),value=TRUE),
                           ident.2 =setdiff(levels(Idents(s)),
                                           grep("NPM1",levels(Idents(s)),value=TRUE)),
                         logfc.threshold=0)
```
--
```{r}
Idents(object = s) <- "seurat_clusters"
all_markers<-FindAllMarkers(s)

all_markers%>%filter(gene%in%c("CD90","CD45RA","CD14")&cluster%in%c(1,2,3))

all_markers %>%
    group_by(cluster) %>%
    slice(1:4)%>%
    top_n(n = 8, wt = avg_log2FC) -> top10

feature_heatmap<-DoHeatmap(s,features = c("CD117","CD34",
                         "FLT3","CD90","CD25",
                         "CD45RA","CD38","CD71",
                         "CD14", "CD11b","CD11c","CD64",
                         "CD2","CD3"),
              group.colors = kelly(n=7)[2:7],
              angle=0,
              raster = FALSE
            )

ggsave(feature_heatmap,
       width=10*.7,
       height=7*.7,
       file="./Results/2022/May/feature_heatmap.pdf")
```

```{r}
# make results dataframe 
d = cbind(s@meta.data, as.data.frame(t(data.frame(s@assays$Protein@data))), s@reductions$umap@cell.embeddings)

d%>%
  dplyr::select(Sample,seurat_clusters)%>%
  data.frame()->out
with(out,  table(seurat_clusters,Sample))%>%data.frame%>%
      ggplot(aes(x=Sample,y=Freq,fill=seurat_clusters))+
      geom_col(position="fill")+
      theme_minimal(base_size=12)+
      scale_fill_manual(values=kelly(n=7)[2:7])->gg_sample_by_cluster

ggsave(gg_sample_by_cluster,
       width=10*.7,
       height=7*.7,
       file="./Results/2022/May/gg_sample_by_cluster.pdf")
```

```{r}
d = cbind(s@meta.data, as.data.frame(t(data.frame(s@assays$Protein@data))), s@reductions$umap@cell.embeddings)

d%>%
  dplyr::select(Clone_Group,seurat_clusters)%>%
  data.frame()->out
with(out,  table(seurat_clusters,Clone_Group))%>%data.frame%>%
    filter(seurat_clusters%in%c(1,2,3))%>%
    filter(Clone_Group%in%c("DNMT3A_FLT3","DNMT3A_NPM1_FLT3","NPM1_FLT3"))
```

```{r}
Idents(object = s) <- "seurat_clusters"

DEG_results<-lapply(c("1","2","3"),function(cluster){

DF<-FindMarkers(s,
                ident.1="DNMT3A_FLT3",
                ident.2 = "DNMT3A",
         #       test.use = "t",
           #     logfc.threshold = 0.25,
                group.by = "Clone_Group",
                subset.ident = c(cluster))%>%
          data.frame()%>%
          rownames_to_column(var="Marker")


DNF<-FindMarkers(s,
                ident.1="DNMT3A_NPM1_FLT3",
                ident.2 = "DNMT3A_NPM1",
            #    test.use = "t",
            #    logfc.threshold = 0.25,
                group.by = "Clone_Group",
                subset.ident = c(cluster))%>%
          data.frame()%>%
          rownames_to_column(var="Marker")

NF<-FindMarkers(s,
                ident.1="NPM1_FLT3",
                ident.2 = "NPM1",
         #       test.use = "t",
            #    logfc.threshold = 0.25,
                group.by = "Clone_Group",
                subset.ident = c(cluster))%>%
          data.frame()%>%
          rownames_to_column(var="Marker")

diff_out<-inner_join(
      inner_join(DF%>%
              dplyr::select(Marker,
                            DF_padj=p_val_adj,
                            DF_FC=avg_log2FC)%>%
                mutate(DF_score=-log10(DF_padj)*sign(DF_FC)),
                 DNF%>%
                    dplyr::select(Marker,
                                  DNF_padj=p_val_adj,
                                  DNF_FC=avg_log2FC))%>%
                mutate(DNF_score=-log10(DNF_padj)*sign(DNF_FC)),
                NF%>%
                    dplyr::select(Marker,
                                  NF_padj=p_val_adj,
                                  NF_FC=avg_log2FC)%>%
                mutate(NF_score=-log10(NF_padj)*sign(NF_FC)))%>%
        dplyr::select(Marker,NF_score,DNF_score,DF_score)%>%
        pivot_longer(cols=-Marker,names_to = "Group",values_to ="score" )

return(diff_out%>%data.frame)
})

diff_out%>%ggplot(aes(x=score,y=Marker,fill=Group))+geom_col(position = position_dodge())
```


```{r}

Idents(object = s) <- "seurat_clusters"

DEG_results<-lapply(c("1","2","3"),function(cluster){

DF_NF<-FindMarkers(s,
                ident.1="DNMT3A_FLT3",
                ident.2 = "NPM1_FLT3",
         #       test.use = "t",
           #     logfc.threshold = 0.25,
                group.by = "Clone_Group",
                subset.ident = c(cluster))%>%
          data.frame()%>%
          rownames_to_column(var="Marker")


DNF_DF<-FindMarkers(s,
                ident.1="DNMT3A_NPM1_FLT3",
                ident.2 = "DNMT3A_FLT3",
            #    test.use = "t",
            #    logfc.threshold = 0.25,
                group.by = "Clone_Group",
                subset.ident = c(cluster))%>%
          data.frame()%>%
          rownames_to_column(var="Marker")

NF_DNF<-FindMarkers(s,
                ident.1="NPM1_FLT3",
                ident.2 = "DNMT3A_NPM1_FLT3",
         #       test.use = "t",
            #    logfc.threshold = 0.25,
                group.by = "Clone_Group",
                subset.ident = c(cluster))%>%
          data.frame()%>%
          rownames_to_column(var="Marker")

diff_out<-inner_join(
      inner_join(DF_NF%>%
              dplyr::select(Marker,
                            DF_NF_padj=p_val_adj,
                            DF_NF_FC=avg_log2FC)%>%
                mutate(DF_NF_score=-log10(DF_NF_padj)*sign(DF_NF_FC)),
                 DNF_DF%>%
                    dplyr::select(Marker,
                                  DNF_DF_padj=p_val_adj,
                                  DNF_DF_FC=avg_log2FC))%>%
                mutate(DNF_DF_score=-log10(DNF_DF_padj)*sign(DNF_DF_FC)),
                NF_DNF%>%
                    dplyr::select(Marker,
                                  NF_DNF_padj=p_val_adj,
                                  NF_DNF_FC=avg_log2FC)%>%
                mutate(NF_DNF_score=-log10(NF_DNF_padj)*sign(NF_DNF_FC)))%>%
        dplyr::select(Marker,DF_NF_score,DNF_DF_score,NF_DNF_score)%>%
        pivot_longer(cols=-Marker,names_to = "Group",values_to ="score" )

return(diff_out%>%data.frame)
})

diff_out%>%ggplot(aes(x=score,y=Marker,fill=Group))+geom_col(position = position_dodge())

```