---
title: "Clonal Evolution Figure 6"
author: "Bowman RL"
date: "12/10/2021"
output: html_document
---

Setup 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/LevineLab/Levine Lab/Bobby/Project Notes/Flt3/")
```

Packages
```{r libraries}
library(tidyverse)
library(DESeq2)
library(RColorBrewer)
library(tidyheatmaps)
library(pals)
library(msigdbr)
library(fgsea)
library(ggrepel)
library(stringr)
library(cowplot)
library(ggrastr)
setwd("/Volumes/LevineLab/Levine Lab/Bobby/Project Notes/Flt3/")
source("./Scripts/extra_functions.R")
```


Load Data 
```{r}
results<-readRDS(file="./Results/2022/May/NF_goldilox_STAR_results.rds")
pheno_select<-readRDS(file="./Results/2022/May/NF_goldilox_STAR_pheno.rds")
norm_counts<-readRDS(file="./Results/2022/May/NF_goldilox_STAR_norm_counts.rds")
long_counts<-readRDS(file="./Results/2022/MayNF_goldilox_STAR_long_counts.rds")
vsd_transformation<-readRDS(file="./Results/2022/May/NF_goldilox_STAR_vsd.rds")

Leuk_complete<-results%>%
                         data.frame%>%
                         rownames_to_column(var="Gene")%>%
                          mutate(score=-log10(padj)*sign(log2FoldChange))%>%
                          arrange(score)%>%
                          filter(!is.na(padj))%>%
                        mutate(Group=case_when(
                          log2FoldChange>1&padj<0.05&baseMean>50~"Up",
                          log2FoldChange<(-1)&padj<0.05&baseMean>50~"Down",
                          TRUE~"Other"
                        ))%>%
                        arrange(padj)%>%
                        mutate(Group=factor(Group,levels=c("Down","Up","Other")))

```

```{r}
write.csv(results%>%data.frame%>%
              rownames_to_column(var="Gene"),
          file="./Mature_analysis/Statistics/TableS1e.csv")
```

GSEA setup
```{R gene set extraction and setup,cache=TRUE}
C2_gene_sets <- msigdbr(species = "Mus musculus", category = "C2")%>%
                          data.frame%>%
                          dplyr::select(gene_symbol,gs_name)%>%
                          split(f = as.factor(.$gs_name))%>%
                          lapply(function(x){x$gene_symbol})

H_gene_sets <- msigdbr(species = "Mus musculus", category = "H")%>%
                          data.frame%>%
                          dplyr::select(gene_symbol,gs_name)%>%
                          mutate(gs_name=gsub("HALLMARK_","",gs_name))%>%
                          split(f = as.factor(.$gs_name))%>%
                          lapply(function(x){x$gene_symbol})
```

Figure 6e
```{r GSEA}
ranked_set<-results%>%
                        data.frame()%>%
                          filter(baseMean>25)%>%
                        mutate(score=log2FoldChange)%>%
                        arrange(score)
ranked_set_final <-ranked_set$score;names(ranked_set_final)<-rownames(ranked_set)


pathway_of_interest<-c("INTERFERON_GAMMA_RESPONSE",
                       "INFLAMMATORY_RESPONSE",
                       "HEME_METABOLISM",
                       "IL6_JAK_STAT3_SIGNALING",
                       "REACTOME_FLT3_SIGNALING_IN_DISEASE",
                       "REACTOME_ERK_MAPK_TARGETS",
                       "HESS_TARGETS_OF_HOXA9_AND_MEIS1_UP",
                       "MTORC1_SIGNALING",
                       "E2F_TARGETS",
                       "MYC_TARGETS_V1",
                       "MYC_TARGETS_V2")

gseaParam=1                       

Figure6e<-multi_track_GSEA(all_pathways=c(H_gene_sets,C2_gene_sets),
                 stats=ranked_set_final, 
                 pathway_of_interest=pathway_of_interest,
                 ticksSize = 4) + theme_classic(base_size=12)


ggsave(Figure6e,
       file="./Mature_analysis/Final_Figures/Figure 6/Figure 6e.pdf",
       width=8,
       height=3)

fgseaRes_H <- fgsea::fgseaMultilevel(pathways = H_gene_sets,
                                    stats    = ranked_set_final,
                               #     eps=0,
                                    minSize  = 15,
                                    maxSize  = 1000)

LinNeg_TAM_GSEA_H<-fgseaRes_H%>%
            data.frame%>%
            mutate(Score=-log10(pval)*sign(NES))%>%
            dplyr::select(pathway,padj,NES)%>%
            arrange((NES))
```

```{r}
write.csv(LinNeg_TAM_GSEA_H,
          file="./Mature_analysis/Statistics/TableS1d-gsea.csv")
```



Extended Data 10e
```{r genes of interest extraction}
genes_of_interest<- c("Hoxa9","Hoxa7","Hoxa10","Myc","Meis1","Mecom","Socs2","Cish",
                      "Pim1","Spp1","Il3ra","Cdk4","Cdk6","Cdk2","Fosb","Jun",
                      "Gata1","Hbb-b1","Hbb-b2","Hba-a1","Epor","Gypa","S100a9","S100a8",
                      "H2-Eb2","H2-Aa",'H2-Ab1',"Irf7","Ciita","Ifng")

long_counts%>%
  filter(Gene%in%genes_of_interest)%>%
  #filter(Cell.type%in%"LSK")%>%
  mutate(Treatment=factor(Treatment, levels=c("Vehicle","TAM")))%>%
  arrange((Treatment))%>%
  tidy_heatmap(rows=Gene,
               columns = sample,
               values = value,
               scale="row",
               annotation_col =c(Treatment),
               colors = rev(brewer.rdbu(n=100)),
               treeheight_row = 0,
               color_legend_n=100,
               cellwidth = 6,
               cellheight = 7,
               show_colnames = FALSE,
               annotation_colors =list("Treatment"=c("Vehicle"=brewer.pal(n=5,"Greys")[3],
                                                    "TAM"=brewer.pal(n=5,"Reds")[5])) ,
               cluster_rows = TRUE,
               file="./Mature_analysis/Final_Figures/Extended Data 10/Extended Data 10e-heatmap.pdf")


```


Extended Data 10f
```{r}
ranked_set<-results%>%
                        data.frame()%>%
                          filter(baseMean>25)%>%
                        mutate(score=log2FoldChange)%>%
                        arrange(score)
ranked_set_final <-ranked_set$score;names(ranked_set_final)<-rownames(ranked_set)


fgseaRes_C2 <- fgsea::fgseaMultilevel(pathways = C2_gene_sets[grepl("KEGG|SERINE|HOXA9|REACTOME",names(C2_gene_sets))],
                                    stats    = ranked_set_final,
                                    minSize  = 15,
                                    nproc=12,
                                    maxSize  = 1000)

LinNeg_TAM_GSEA_C2<-fgseaRes_C2%>%
                        data.frame%>%
                        mutate(Score=-log10(pval)*sign(NES))%>%
                        dplyr::select(pathway,pval,Score,padj,NES)%>%
                        filter(grepl("SERINE",pathway))%>%
                        arrange((NES))


```

GSEA plots
```{r}
gsea_stat5_lsk_2w<-plotEnrichment(C2_gene_sets$KEGG_GLYCINE_SERINE_AND_THREONINE_METABOLISM,ranked_set_final) + 
                labs(title="KEGG: Glycine Serine and Threonine Metabolism \n Down with Flt3 deletion")+
                theme(plot.title=element_text(hjust=0.5))
ggsave(gsea_stat5_lsk_2w,file="./Figures/gsea_stat5_lsk_2w.pdf",
      width=4,
      height=2.5)
```


