---
title: "Clonal Evolution Extended Data 4de"
author: "Robert Bowman"
date: "5/12/2022"
output: html_document
---


Setup and Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Volumes/Bowman Lab/Lab Personal/Bobby/Project Notes/FLT3_GL/")
```

Data Sets
```{r, message=FALSE}
library(tidyverse)
library(cowplot)
library(RColorBrewer)
library(pals)
setwd("/Volumes/Bowman Lab/Lab Personal/Bobby/Project Notes/FLT3_GL/")
source("./Scripts/extra_functions.R")

results<-readRDS("./Results/2022/May/NF_vs_DF_STAR_results.rds")
pheno_select<-readRDS(file="./Results/2022/May/NF_vs_DF_STAR_pheno.rds")
norm_counts<-readRDS(file="./Results/2022/May/NF_vs_DF_STAR_norm_counts.rds")
long_counts<-readRDS(file="./Results/2022/May/NF_vs_DF_STAR_long_counts.rds")
vsd_transformation<-readRDS(file="./Results/2022/May/NF_vs_DF_STAR_vsd.rds")
```


GSEA Gene set extraction
```{R gene set extraction and setup,cache=TRUE}
library(fgsea)
library(msigdbr)
C2_gene_sets <- msigdbr(species = "Mus musculus", category = "C2")%>%
                          data.frame%>%
                          dplyr::select(gene_symbol,gs_name)%>%
                          split(f = as.factor(.$gs_name))%>%
                          lapply(function(x){x$gene_symbol})
H_gene_sets <- msigdbr(species = "Mus musculus", category = "H")%>%
                          data.frame%>%
                          dplyr::select(gene_symbol,gs_name)%>%
                          mutate(gs_name=gsub("HALLMARK_","",gs_name))%>%
                          split(f = as.factor(.$gs_name))%>%
                          lapply(function(x){x$gene_symbol})
```


Extended Data 4d
```{r genes of interest extraction}
library(tidyheatmaps)
LSK_FN_v_FD<-results$LSK_Flt3_Npm1$LSK_Flt3_Npm1_VS_LSK_Flt3_Dnmt3a%>%
                        data.frame()%>%
                        filter(!is.na(padj))%>%
                        mutate(Group=case_when(
                          log2FoldChange>1&padj<0.05~"Up",
                          log2FoldChange<(-1)&padj<0.05~"Down",
                          TRUE~"Other"
                        ))%>%
                        rownames_to_column(var = "Gene")%>%
                        arrange((padj))%>%
                        mutate(Group=factor(Group,levels=c("Down","Up","Other")))

TNF<-intersect(H_gene_sets$TNFA_SIGNALING_VIA_NFKB,LSK_FN_v_FD%>%filter(Group=="Up")%>%pull(Gene))

TNF_genes<-c("Il12b", "Mcl1","Nfil3","Nfkbia","Nr4a1","Nr4a3",
                     "Ifngr2","Ccl4","Ccl5","Tnf",
                     "Cd80","Cd83","Cdkn1a","Cebpd","Cxcl10",
                     "Bcl2a1a","Bcl3","Bcl6"  
                     )


genes_of_interest<-c("Atf3","Aurka","Aurkb","B2m","Bcl3","Bcl6","Ccl4","Ccl5","Ccnd1","Cd40","Cd74","Cenpe","Ciita","Chek1","Chek2","Csf2rb2","Cxcl10","Dusp1","Dusp2","Dusp4","Dusp5","E2f8","Egr1","Egr2","Egr3","Fos","Fosb","H2-DMa","Id2","Ido1","Ifngr2","Il12b","Il1b","Il6st","Irf4","Irf5","Irf7","Mx1","Mx2","Tnf","Socs1","Xpo1","Vegfa","Smad3","Pim1","Ccnb2","Cdkn2c","Mcm2","Mcm4","Mcm6","Rrm2","Top2a","Pole","Melk","Msh2","Bub1b","Grb7","Gpr56","Hoxa9","Hoxa10","Hoxa7")



long_counts%>%
  filter(Gene%in%genes_of_interest)%>%
  filter(Cell.type%in%"LSK")%>%
  mutate(gene_set = case_when(
    Gene%in%TNF_genes~"TNF-NFkB",
    Gene%in%Hox
  )
  arrange(Cell.type,(Genotype))%>%
  tidy_heatmap(columns=sample,
               rows = Gene,
               values = value,
               scale="row",
             #  angle_col=45,
               fontsize = 7,
               annotation_col =c(Genotype),
               colors = rev(brewer.rdbu(n=100)),
               treeheight_col = 0,
               color_legend_n=100,
            #   gaps_row = Cell.type,
               cellwidth = 8,
               cellheight = 5,
               show_colnames = F,
               show_rownames = T,
               annotation_colors =list("Genotype"=c("Flt3_Dnmt3a"=brewer.pal(n=5,"Oranges")[3],
                                                    "Flt3_Npm1"=brewer.pal(n=5,"Greens")[5])#,
                                       # "Cell.type"=c("LSK"=brewer.pal(n=5,"Purples")[5],
                                      #                "GMP"=brewer.pal(n=5,"Oranges")[5])
                                       ),
               cluster_rows = TRUE,
               file="./Mature_analysis/Final_Figures/Extended Data 3/Extended Data 3i-heatmap_v3_LSK_only.pdf")


```



Extended Data 4e
```{r}
library(ggrepel)
ranked_set<-results$GMP_Flt3_Npm1$LS<_Flt3_Npm1_VS_LSK_Flt3_Dnmt3a%>%
                        data.frame()%>%
                        filter(baseMean>25)%>%
                        mutate(score=-log10(pvalue)*sign(log2FoldChange))%>%
                        arrange(desc(log2FoldChange))
ranked_set_final <-ranked_set$score
names(ranked_set_final)<-rownames(ranked_set)

fgseaRes <- fgsea::fgseaMultilevel(pathways = H_gene_sets,
                                    stats    = ranked_set_final,
                                    minSize  = 15,
                                    maxSize  = 1000)

LSK_NF_DF_GSEA<-fgseaRes%>%
            data.frame%>%
            dplyr::select(pathway,pval,padj,NES)%>%
            mutate(Score=-log10(pval)*sign(NES))%>%
            arrange((Score))%>%
            mutate(pathway=factor(pathway,levels=pathway))%>%
            mutate(label=ifelse(padj<0.01,as.character(pathway),""))%>%
            mutate(Significant=ifelse(label=="","No","Yes"))%>%
            ggplot(aes(x=pathway,color=Significant,
                       label=label,y=(-log10(pval)*sign(NES) )))+
                  geom_point()+
                  scale_color_manual(values=c("Yes"=brewer.pal(5,"Reds")[5],
                                              "No"=brewer.pal(5,"Greys")[3]))+
                  theme_classic(base_size=16)+
                  geom_hline(yintercept = 0)+
                  geom_text_repel(color="black",size=4)+
                  ylab("Enrichment: -log10(p)*sign")+
                  guides(color="none")+
                  theme(axis.line.x=element_line(),
                        axis.line.y=element_line(),
                        axis.ticks.x = element_blank(),
                        axis.text.x = element_blank())
  
ggsave(LSK_NF_DF_GSEA,file="./Mature_analysis/Final_Figures/Extended Data 4/Extended Data 4e-gsea.pdf",
      width=4,
      height=4)

write.csv(LSK_NF_DF_GSEA,
          file="./Mature_analysis/Statistics/TableS1b.csv")
```

```{r}
out<-fgseaRes%>%
            data.frame%>%
            dplyr::filter(padj<0.1)%>%
            dplyr::select(pathway,pval,padj,NES)%>%
            mutate(Score=-log10(pval)*sign(NES))%>%
            arrange(abs(Score))%>%
            dplyr::slice(1:15)%>%
            arrange(desc((NES)))%>%
            pull(pathway)

gseaParam = 1

GSEA_multi_LSK<-multi_track_GSEA(all_pathways = H_gene_sets,
                 stats=-1*ranked_set_final%>%sort,
                 pathway_of_interest=out,
                 ticksSize = 4)+ylab("")+
                 theme_classic(base_size=12)+
                 scale_y_discrete(position="right")+
scale_colour_gradient2(
  high = brewer.pal(n=5,name="Oranges")[3],
  mid = brewer.pal(n=5,name="Greys")[2],
  low = brewer.pal(n=5,name="Greens")[5],
  midpoint = 7514,
  space = "Lab",
  na.value = "grey50",
  guide = "colourbar",
  aesthetics = "colour"
)          +
  theme(plot.margin=margin(l=0,r=0.25,unit="cm"))+
                 theme(#axis.text.y.=element_blank(),
                          axis.line.y.right = element_blank(),
                                    axis.text.x=element_text(size=12),
                          axis.ticks.y.right  = element_blank(),
                          axis.title.y.right = element_blank())

NES_Bar<- fgseaRes%>%
            data.frame%>%
            dplyr::filter(padj<0.1)%>%
            dplyr::select(pathway,pval,padj,NES)%>%
            mutate(Score=-log10(pval)*sign(NES))%>%
            arrange(abs(Score))%>%
            dplyr::slice(1:15)%>%
              arrange(((NES)))%>%
    mutate(pathway=factor(pathway,levels=pathway))%>%
    ggplot(aes(x=NES,y=pathway))+
    geom_col(fill="grey80",width = 0.75)+
    xlab("NES")+
    scale_y_discrete(position="right")+
    theme_classic(base_size=12)+
 #   scale_x_continuous(limits = c(-2,0),
#                      breaks=c(-2,-1.5,-1,-0.5),
#                      labels =c(-2,-1.5,-1,-0.5) )+
    theme(axis.text.y=element_blank(),
          axis.ticks.y=element_blank(),
          axis.text.x=element_text(size=12),
          axis.title.y=element_blank())+
        theme(plot.margin=margin(r=0,l=0.1,unit="cm"))


  ggsave(
    plot_grid(NES_Bar,
                   GSEA_multi_LSK,
                   ncol=2,
                   align = "h",
                   axis="bt",
                   rel_widths = c(0.25,1.5))#,align="hv")#,axis = "tb")
       
      ,width=6,height=3.5,
         file="./Mature_analysis/Final_Figures/Figure 2/Figure2e-LSK_multi_GSEA-with-bars-final.pdf")


```

```{r}
library(ggrastr)
results$LSK_Flt3_Npm1$LSK_Flt3_Npm1_VS_LSK_Flt3_Dnmt3a%>%
    data.frame()%>%
    rownames_to_column(var="Gene")%>%
    mutate(Group=case_when(
      log2FoldChange>log2(1.5)&padj<0.05~"NF",
      log2FoldChange<(-log2(1.5))&padj<0.05~"DF",
      TRUE~"Other"
    ))->results_out

results_out%>%arrange(log2FoldChange)%>%filter(!is.na(padj)&baseMean>25)

NF_genes<-c("Hoxa7","Cd34","Tyrobp","Sel1","Grb7","Atf3","Irf8","H2-Aa",
            "Stk11","Tlr13","Lifr","Cd36","Mcl1","Itgax","H2-DMa")
NF_genes<-c("Atf3","Aurka","Aurkb","B2m","Bcl3","Bcl6","Ccl4","Ccl5","Ccnd1","Cd40","Cd74","Cenpe","Ciita","Chek1","Chek2","Csf2rb2","Cxcl10","Dusp1","Dusp2","Dusp4","Dusp5","E2f8","Egr1","Egr2","Egr3","Fos","Fosb","H2-DMa","Id2","Ido1","Ifngr2","Il12b","Il1b","Il6st","Irf4","Irf5","Irf7","Mx1","Mx2","Tnf","Socs1","Xpo1","Vegfa","Smad3","Pim1","Ccnb2","Cdkn2c","Mcm2","Mcm4","Mcm6","Rrm2","Top2a","Pole","Melk","Msh2","Bub1b","Grb7","Gpr56")
ggplot(results_out,aes(x=log2FoldChange,y=-log10(padj),color=Group))+
geom_point_rast()+
scale_color_manual(values=c("DF"=brewer.pal(n=5,name="Oranges")[3],
                            "NF"=brewer.pal(n=5,name="Greens")[5],
                            "Other"="grey"))+
theme_classic()+
geom_label(data=results_out%>%filter(Gene%in%(NF_genes)),
             aes(x=log2FoldChange,y=-log10(padj),color=Group,label=Gene))
```